# Generated by Django 3.1.2 on 2020-10-22 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carparkingreservation',
            name='disabled_space',
        ),
    ]
